import type { RemoteCap } from './cap-fetch';

// Mock data for development (will be replaced with real API calls)
export const mockRemoteCaps: RemoteCap[] = [
  {
    id: '1',
    name: 'Code Generator',
    tag: 'development',
    description:
      'Generate high-quality code snippets and functions for various programming languages.',
    downloads: 1250,
    version: '1.2.0',
    author: 'CodeCraft Team',
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000, // 30 days ago
    updatedAt: Date.now() - 7 * 24 * 60 * 60 * 1000, // 7 days ago
    size: 2.5,
  },
  {
    id: '2',
    name: 'UI Designer',
    tag: 'design',
    description:
      'Create beautiful user interfaces and design systems with modern components.',
    downloads: 890,
    version: '2.1.0',
    author: 'DesignLab',
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    size: 1.8,
  },
  {
    id: '3',
    name: 'Data Analyzer',
    tag: 'analytics',
    description:
      'Analyze complex datasets and generate insightful reports and visualizations.',
    downloads: 567,
    version: '1.0.3',
    author: 'DataViz Pro',
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
    size: 3.2,
  },
  {
    id: '4',
    name: 'Content Writer',
    tag: 'productivity',
    description:
      'Write engaging content, articles, and marketing copy with AI assistance.',
    downloads: 2100,
    version: '3.0.1',
    author: 'ContentAI',
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    size: 1.2,
  },
  {
    id: '5',
    name: 'Image Editor',
    tag: 'design',
    description:
      'Edit and enhance images with advanced AI-powered tools and filters.',
    downloads: 1850,
    version: '1.5.2',
    author: 'PixelCraft',
    createdAt: Date.now() - 75 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    size: 4.1,
  },
  {
    id: '6',
    name: 'API Builder',
    tag: 'development',
    description:
      'Build and test REST APIs with automatic documentation generation.',
    downloads: 923,
    version: '2.0.0',
    author: 'APITools Inc',
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    size: 2.8,
  },
  {
    id: '7',
    name: 'Task Manager',
    tag: 'productivity',
    description:
      'Organize tasks, set priorities, and track project progress efficiently.',
    downloads: 1567,
    version: '1.3.1',
    author: 'ProductivePro',
    createdAt: Date.now() - 50 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 8 * 24 * 60 * 60 * 1000,
    size: 1.9,
  },
  {
    id: '8',
    name: 'Chart Builder',
    tag: 'analytics',
    description:
      'Create interactive charts and graphs from your data with ease.',
    downloads: 734,
    version: '1.1.0',
    author: 'ChartMaster',
    createdAt: Date.now() - 35 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
    size: 2.3,
  },
  {
    id: '9',
    name: 'Password Generator',
    tag: 'security',
    description: 'Generate secure passwords and manage credentials safely.',
    downloads: 2890,
    version: '2.2.0',
    author: 'SecureTech',
    createdAt: Date.now() - 100 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    size: 0.8,
  },
  {
    id: '10',
    name: 'Color Palette',
    tag: 'design',
    description: 'Generate beautiful color palettes for your design projects.',
    downloads: 1290,
    version: '1.4.0',
    author: 'ColorGenius',
    createdAt: Date.now() - 65 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 6 * 24 * 60 * 60 * 1000,
    size: 1.1,
  },
  {
    id: '11',
    name: 'Database Query',
    tag: 'development',
    description: 'Write and optimize SQL queries with AI-powered suggestions.',
    downloads: 456,
    version: '1.0.1',
    author: 'QueryCraft',
    createdAt: Date.now() - 25 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    size: 1.7,
  },
  {
    id: '12',
    name: 'Security Scanner',
    tag: 'security',
    description:
      'Scan your applications for security vulnerabilities and threats.',
    downloads: 678,
    version: '1.6.0',
    author: 'SecScan Labs',
    createdAt: Date.now() - 80 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
    size: 3.5,
  },
];
